"""Your prompts, and what each one set off: splitting at prompts, attributing work, and showing it."""

import json
import tempfile
import time
import unittest
from types import SimpleNamespace as NS

from orchestra import turns as T
from orchestra.livestate import ANSWERED, Wait
from orchestra.pricing import PriceTable
from tests import fake_secrets as fake
from tests.fixtures import ts

PRICES = PriceTable.parse({"currency": "USD", "models": {
    "claude-sonnet*": {"input": 3.0, "output": 15.0, "cache_read": 0.3, "cache_create": 3.75}}})


def you(at, text, source="typed", **extra):
    entry = {"type": "user", "timestamp": ts(at), "promptId": "p%d" % at, "promptSource": source,
             "message": {"role": "user", "content": text}}
    entry.update(extra)
    return entry


def call(mid, at, out=100, model="claude-sonnet-5-5", blocks=None):
    return {"type": "assistant", "timestamp": ts(at), "message": {
        "id": mid, "role": "assistant", "model": model, "content": blocks or [{"type": "text", "text": "x"}],
        "usage": {"input_tokens": 10, "output_tokens": out, "cache_read_input_tokens": 1000}}}


def tool(uid, name, **params):
    return {"type": "tool_use", "id": uid, "name": name, "input": params}


def result(uid, at, is_error=False):
    return {"type": "user", "timestamp": ts(at), "message": {"role": "user", "content": [
        {"type": "tool_result", "tool_use_id": uid, "content": "ok", "is_error": is_error}]}}


def turn_end(at):
    return {"type": "system", "subtype": "turn_duration", "timestamp": ts(at), "durationMs": 1000}


def log(*entries):
    out = T.TurnLog()
    out.ingest(list(entries))
    return out


class TestPrompts(unittest.TestCase):
    def test_what_counts_as_a_prompt(self):
        self.assertEqual(T.prompt_of(you(1, "  fix the tests  ")), "fix the tests")
        blocks = you(1, [{"type": "text", "text": "look at"}, {"type": "image", "source": {}}, {"type": "text", "text": "this"}])
        self.assertEqual(T.prompt_of(blocks), "look at this")
        for not_a_prompt in (result("t", 1), you(1, "x", isMeta=True), you(1, "x", isSidechain=True),
                             you(1, "<task-notification><task-id>a</task-id></task-notification>"),
                             you(1, "<local-command-stdout>done</local-command-stdout>"),
                             you(1, "<system-reminder>be brief</system-reminder>"),
                             you(1, "Caveat: The messages below were generated by the user"), you(1, "   "),
                             {"type": "assistant", "message": {"content": "hi"}}):
            self.assertIsNone(T.prompt_of(not_a_prompt), not_a_prompt)

    def test_slash_commands_read_as_typed_and_text_is_bounded_and_scrubbed(self):
        cmd = you(1, "<command-name>/cuelight:open</command-name>\n<command-message>cuelight:open</command-message>\n"
                     "<command-args>stop</command-args>")
        self.assertEqual(T.prompt_of(cmd), "/cuelight:open stop")
        long = T.prompt_of(you(1, "use " + fake.GITHUB_TOKEN + " " + "word " * 200))
        self.assertLessEqual(len(long), T.MAX_PROMPT)
        self.assertTrue(long.endswith("…"))
        self.assertNotIn("ABCDEFGHIJKLMNOP", long)


class TestLog(unittest.TestCase):
    def test_usage_tools_and_edits_land_in_their_prompt(self):
        l = log(call("before", 0),                                   # before any prompt: not attributed
                you(10, "first"), call("m1", 11, blocks=[tool("e1", "Edit", file_path="/p/a.py")]),
                result("e1", 15), call("m1", 16, out=300),                # streamed copy: latest usage wins
                call("m2", 17, blocks=[tool("e2", "Write", file_path="/p/b.py")]), result("e2", 18, is_error=True),
                turn_end(20),
                you(30, "second"), call("m3", 31))
        first, second = l.turns
        self.assertEqual((first["prompt"], first["record_at"] is not None, sorted(first["edits"])),
                         ("first", True, ["/p/a.py"]))
        self.assertEqual(first["spans"][0][1] - first["spans"][0][0], 4)
        usage = l.usage_by_turn()
        self.assertEqual(usage[0]["claude-sonnet-5-5"]["output"], 300 + 100)
        self.assertEqual(usage[1]["claude-sonnet-5-5"]["output"], 100)
        self.assertEqual(second["record_at"], None)

    def test_snapshot_is_frozen(self):
        l = log(you(1, "a"))
        snap = l.snapshot()
        l.ingest([you(5, "b")])
        self.assertEqual((len(snap.turns), len(l.turns)), (1, 2))


def agent(aid, start, end, tokens=None, files=()):
    return NS(agent_id=aid, started_at=T.parse_timestamp(ts(start)),
              ended_at=T.parse_timestamp(ts(end)) if end is not None else None,
              tokens_by_model=tokens or {}, outcomes=None,
              changes=NS(files={f: NS(scratch=f.startswith("/tmp")) for f in files}))


def run(agents=(), waits=(), live=False, commits=None):
    return NS(agents=list(agents), waits=list(waits), session_live=live,
              main_outcomes=NS(commits=commits or {}))


class TestSummary(unittest.TestCase):
    def test_the_time_split_adds_up_and_each_moment_counts_once(self):
        l = log(you(0, "build it"), call("m1", 1, blocks=[tool("b", "Bash", command="npm test")]),
                result("b", 61), call("m2", 100), turn_end(100))
        start = T.parse_timestamp(ts(0))
        waits = [Wait(agent_id="a1", kind="permission", start=start + 40, end=start + 70, state=ANSWERED)]
        s = T.summary(l, run([agent("a1", 30, 90)], waits), None, now=start + 500)
        [row] = s["rows"]
        self.assertEqual(row["seconds"], 100)
        # waiting 40-70; agents and tools 1-40 and 70-90; Claude itself the rest
        self.assertEqual(row["split"], {"you": 30, "work": 59, "claude": 11})
        self.assertEqual(sum(row["split"].values()), row["seconds"])

    def test_agents_commits_and_files_are_matched_to_the_prompt_that_started_them(self):
        l = log(you(0, "plan"), call("m1", 1, blocks=[tool("e", "Edit", file_path="/p/plan.md")]), result("e", 2),
                you(100, "build"), call("m2", 101))
        commits = {"k1": {"at": T.parse_timestamp(ts(150))}}
        r = run([agent("a1", 10, 50, files=("/p/x.py", "/tmp/scratch.py")), agent("a2", 120, 180, files=("/p/x.py",))],
                commits=commits)
        s = T.summary(l, r, None, now=T.parse_timestamp(ts(400)))
        plan, build = s["rows"]
        self.assertEqual((plan["agents"], plan["files"], plan["commits"]), (1, 2, 0))
        self.assertEqual((build["agents"], build["files"], build["commits"]), (1, 1, 1))
        self.assertEqual(plan["file_names"], ["/p/plan.md", "/p/x.py"])
        self.assertEqual(build["commit_list"], [{"sha": "", "message": ""}])
        self.assertEqual(build["seconds"], 80)          # until its agent finished

    def test_cost_and_the_most_expensive_prompt(self):
        l = log(you(0, "cheap"), call("m1", 1, out=100), you(10, "dear"), call("m2", 11, out=900))
        s = T.summary(l, run(), PRICES, now=T.parse_timestamp(ts(50)))
        self.assertEqual((s["top"]["prompt"], s["top"]["by"], s["currency"]), ("dear", "cost", "USD"))
        self.assertAlmostEqual(s["rows"][1]["cost"], (10 * 3 + 900 * 15 + 1000 * 0.3) / 1e6)
        self.assertGreater(s["top"]["share"], 0.5)
        plain = T.summary(l, run(), None, now=T.parse_timestamp(ts(50)))
        self.assertEqual((plain["top"]["by"], plain["rows"][1]["cost"]), ("tokens", None))

    def test_local_commands_are_left_out_and_the_live_prompt_counts_up(self):
        l = log(you(0, "<command-name>/plugin</command-name>"), you(5, "go"), call("m1", 6))
        s = T.summary(l, run(live=True), None, now=T.parse_timestamp(ts(65)))
        [row] = s["rows"]
        self.assertEqual((row["prompt"], row["n"], row["ongoing"]), ("go", 2, True))
        self.assertEqual(s["median_s"], None)

    def test_nothing_is_none(self):
        self.assertIsNone(T.summary(T.TurnLog(), run(), None, 0))
        # Found on a real session: only local commands, so every prompt is left out.
        only_local = log(you(0, "<command-name>/plugin</command-name>"), you(5, "<command-name>/model</command-name>"))
        self.assertIsNone(T.summary(only_local, run(), None, T.parse_timestamp(ts(9))))
        # ... and the last of them in a live session is not "still running": Claude Code marks it local.
        marked = log(you(0, "<command-name>/plugin</command-name>"),
                     {"type": "system", "subtype": "local_command", "timestamp": ts(1), "content": "done"})
        self.assertIsNone(T.summary(marked, run(live=True), None, T.parse_timestamp(ts(9))))
        self.assertIsNone(T.summary(None, run(), None, 0))


class TestBuiltAndShown(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from orchestra import demo
        from orchestra.build import RunBuilder
        cls.now = time.time()
        cls.paths, cls.agents = demo.build_demo(tempfile.mkdtemp(), now=cls.now)
        cls.builder = RunBuilder(cls.paths, now_fn=lambda: cls.now + 10)
        cls.built = cls.builder.refresh()

    def test_the_demo_has_its_three_prompts(self):
        p = self.built.insights["prompts"]
        self.assertEqual(p["prompts"], 3)
        self.assertEqual([r["agents"] for r in p["rows"]], [4, 6, 3])
        self.assertTrue(p["rows"][-1]["ongoing"])

    def test_what_the_main_session_recorded_survives_later_reads(self):
        from orchestra import demo
        demo.Simulator(self.paths, self.agents).tick(now=self.now + 5)
        self.assertEqual(self.builder.refresh().insights["prompts"]["prompts"], 3)

    def ui(self):
        from tests import test_insights_ui as ui
        if ui.NODE is None:
            self.skipTest("node is not on PATH")
        return ui

    FNS = ("esc", "fmtDuration", "fmtCount", "fmtPct", "fmtMoney", "fmtClock", "statusVar", "insMetric",
           "insCard", "insEmpty", "fileLabel", "promptsHtml")

    def tab(self, mutate=None, events=True):
        ui = self.ui()
        summary = ui.demo_run(mutate, events=events)
        return ui.run_js(self.FNS, [], "console.log(JSON.stringify(promptsHtml(%s, %s)));"
                         % (json.dumps(summary["insights"]["prompts"]), json.dumps(summary)))

    def test_the_tab(self):
        html = self.tab()
        self.assertIn("Design looks good. Build it", html)
        self.assertIn("of this session&#39;s cost went to prompt #3", html)
        self.assertIn("1m 14s waiting on you", html)
        self.assertIn('class="split-you"', html)
        self.assertIn('<details data-prompt="2">', html)
        self.assertIn("Implement the cart service", html)        # an agent it launched, by name
        self.assertIn('data-agent="a', html)
        for bad in ("NaN", "undefined", "null"):
            self.assertNotIn(bad, html)

    def test_hostile_prompts_are_text(self):
        evil = '"><img src=x onerror=alert(1)>'

        def hit(summary):
            p = summary["insights"]["prompts"]
            p["top"]["prompt"] = evil
            for r in p["rows"]:
                r["prompt"], r["source"], r["file_names"] = evil, evil, [evil]
                r["commit_list"] = [{"sha": evil, "message": evil}]
            for a in summary["agents"]:
                a["description"] = evil
        self.assertNotIn("<img", self.tab(hit))

    def test_it_is_a_tab_of_its_own_and_not_an_insights_card(self):
        ui = self.ui()
        js, html = ui.read("app.js"), ui.read("index.html")
        self.assertIn('data-view="prompts"', html)
        self.assertIn('id="view-prompts"', html)
        self.assertIn('["prompts", "Prompts", "4"]', js)
        self.assertIn('"12345678".indexOf(key)', js)
        self.assertNotIn("Your prompts", ui.render_insights(ui.demo_run()))
        from orchestra import report
        i = report._SHELL.index('data-view="prompts"')
        self.assertNotIn("hidden", report._SHELL[i - 60:i])   # static reports keep it

if __name__ == "__main__":
    unittest.main()
